apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
stringData:
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | default (randAlphaNum 16)  | quote }}
  {{- if not .Values.registry.credentials.existingSecret }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password  | quote }}
  {{- end }}
  {{- template "harbor.traceJaegerPassword" . }}
