apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.core" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
stringData:
  {{- if not .Values.existingSecretSecretKey }}
  secretKey: {{ .Values.secretKey |  quote }}
  {{- end }}
  secret: {{ .Values.core.secret | default (randAlphaNum 16) |  quote }}
  {{- if not .Values.core.secretName }}
  tls.crt: {{ .Files.Get "cert/tls.crt" |  quote  }}
  tls.key: {{ .Files.Get "cert/tls.key" |  quote  }}
  {{- end }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword |  quote }}
  {{- if not .Values.database.external.existingSecret }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
  {{- end }}
  {{- if not .Values.registry.credentials.existingSecret }}
  REGISTRY_CREDENTIAL_PASSWORD: {{ .Values.registry.credentials.password |  quote }}
  {{- end }}
  CSRF_KEY: {{ .Values.core.xsrfKey | default (randAlphaNum 32) |  quote }}
  {{- template "harbor.traceJaegerPassword" . }}
