{{- if .Values.trivy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.trivy" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
stringData:
  redisURL: {{ include "harbor.redis.urlForTrivy" .  }}
  gitHubToken: {{  .Values.trivy.gitHubToken | default ""  | quote }}
{{- end }}
