{{- if .Values.metrics.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.exporter" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
stringData:
{{- if not .Values.exporter.secretName }}
  tls.crt: {{ .Files.Get "cert/tls.crt" | quote }}
  tls.key: {{ .Files.Get "cert/tls.key" | quote }}
{{- end }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword  | quote }}
{{- if not .Values.database.external.existingSecret }}
  HARBOR_DATABASE_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
{{- end }}
{{- end }}
